name: Daily Percy Redeploy

on:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00 UTC (8am ET)
  workflow_dispatch: # allows manual runs

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger dummy commit
        run: |
          git config --global user.name "Percy"
          git config --global user.email "percy@justinmusic.ai"
          echo "// Percy heartbeat" >> ping.js
          git add ping.js
          git commit -m "🤖 Percy ping: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
